### ISSUE TITLE
Release 5.0.5 - Changed Data attachments honor names now isn't working

### ISSUE THREAD

**Issue by kontownik** [reportportal/agent-java-cucumber6#15]
I think it's not working as expected at least in my case, someone moved my issue to a different repository, details: https://github.com/reportportal/reportportal/issues/1176

**Comment by HardNorth** [comment]
@kontownik I was me who moved your issue, since no agents are related to it. 
First of all, you posted you used `ReportPortalHelper` class. There is no such class in any our agent, nor in cucumber6 specifically. It's your or third-party written class. Report Portal is nothing to do with that.

Second, as you posted an example JSON you should see that it's server who renames your file, but you still trying to open an issue in an agent project. Please don't do this.
