### ISSUE TITLE
Introduction (or change) of aspectj binding inside agent-java-cucumber6 breaks build of tests

### ISSUE THREAD

**Issue by JuergenKindler** [reportportal/agent-java-cucumber6#46]
**Describe the bug**
When I try to update to version from 5.3.1 to 5.3.2 I get multiple compile errors in my gradle build.
Seems something was changed added that is incompatible with existing / explicit usage of AspectJ.

**Steps to Reproduce**
Use aspectj in your test code explicitly.

**Expected behavior**
The implementation of the agent should not disrupt other, unrelated code.
There should be no errors during build or runtime.

**Actual behavior**
Compile fails with multiple errors about missing classes although I just changed the version in my `build.gradle` file:
```
<...>/CryoAspect.java:5: error: package org.aspectj.lang does not exist
import org.aspectj.lang.ProceedingJoinPoint;
                       ^
<...>/CryoAspect.java:6: error: package org.aspectj.lang.annotation does not exist
import org.aspectj.lang.annotation.Around;
                                  ^
<...>/CryoAspect.java:7: error: package org.aspectj.lang.annotation does not exist
import org.aspectj.lang.annotation.Aspect;
                                  ^
<...>/CryoAspect.java:14: error: cannot find symbol
@Aspect
 ^
  symbol: class Aspect
<...>/CryoAspect.java:31: error: cannot find symbol
    public String processElement(ProceedingJoinPoint joinPoint) {
                                ^
  symbol:   class ProceedingJoinPoint
  location: class CryoAspect
<...>/CryoAspect.java:27: error: cannot find symbol
    @Around(value = "within(@xxx.DecryoValue *) && ("
     ^
  symbol:   class Around
  location: class CryoAspect
```

**Dependency versions**
client-java: **5.2.13**
agent-java-cucumber6: **5.3.2**

**Additional context**

**Comment by HardNorth** [comment]
@JuergenKindler Yes, because this dependency was marked as `implementation` in the new release. This means it is hidden from user now, and actually I'm thinking of removing it at all, sine this is pure auxiliary dependency and not all of our users use need AspectJ.

It was generally a mistake that we specified it as `api` and share to users, users should control their code not us. So to address this issue please choose and specify your own version of [AspectJ](https://central.sonatype.com/artifact/org.aspectj/aspectjrt).

**Comment by JuergenKindler** [comment]
Thanks a lot @HardNorth !
